"""add_embedding_vector_column

Revision ID: 09d9469046c4
Revises: 74f66382e399
Create Date: 2026-04-13 17:34:03.607666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '09d9469046c4'
down_revision: Union[str, Sequence[str], None] = '74f66382e399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_embeddings', sa.Column('embedding', Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_embeddings', 'embedding')
    # ### end Alembic commands ###
