"""initial_schema_v1

Revision ID: 74f66382e399
Revises: 
Create Date: 2026-04-13 17:00:19.610004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74f66382e399'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_nodes',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_tier', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('topic_description', sa.String(), nullable=True),
    sa.Column('initial_knowledge_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'PRO', name='knowledgelevel', native_enum=False), nullable=False),
    sa.Column('current_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'PRO', name='knowledgelevel', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('concept_node_id', sa.UUID(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_node_id'], ['concept_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_edges',
    sa.Column('from_node_id', sa.UUID(), nullable=False),
    sa.Column('to_node_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('PREREQUISITE', 'RELATED', 'EXTENDS', name='relationtype', native_enum=False), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['concept_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['concept_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_node_id', 'to_node_id', 'relation_type', name='uq_concept_edge')
    )
    op.create_table('concept_mastery',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_node_id', sa.UUID(), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('total_answers', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('review_interval_days', sa.Float(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_node_id'], ['concept_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_node_id', name='uq_user_concept')
    )
    op.create_table('content_embeddings',
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('concept_node_id', sa.UUID(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_summary', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_node_id'], ['concept_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learning_style', sa.String(), nullable=True),
    sa.Column('pace_preference', sa.String(), nullable=True),
    sa.Column('explanation_detail_level', sa.String(), nullable=True),
    sa.Column('preferred_code_complexity', sa.String(), nullable=True),
    sa.Column('analogy_preference', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=True),
    sa.Column('avg_session_duration_minutes', sa.Float(), nullable=True),
    sa.Column('preferred_session_time', sa.String(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('longest_streak_days', sa.Integer(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('strengths_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('topic_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.String(), nullable=False),
    sa.Column('quizzes_attempted', sa.Integer(), nullable=True),
    sa.Column('quizzes_correct', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False), nullable=False),
    sa.Column('message_type', sa.Enum('EXPLANATION', 'DOUBT', 'QUIZ', 'GENERAL', name='messagetype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to_message_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('SESSION_START', 'SESSION_END', 'MESSAGE_SENT', 'QUIZ_STARTED', 'QUIZ_COMPLETED', 'EXPLANATION_VIEWED', 'HINT_REQUESTED', 'FEEDBACK_GIVEN', 'RESOURCE_CLICKED', name='eventtype', native_enum=False), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=True),
    sa.Column('concept_node_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['concept_node_id'], ['concept_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_feedback',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('feedback_category', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_attempts')
    op.drop_table('message_feedback')
    op.drop_table('quizzes')
    op.drop_table('engagement_events')
    op.drop_table('chat_messages')
    op.drop_table('topic_progress')
    op.drop_table('learner_profiles')
    op.drop_table('content_embeddings')
    op.drop_table('concept_mastery')
    op.drop_table('concept_edges')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('concept_nodes')
    # ### end Alembic commands ###
