"""add_learner_summary

Revision ID: 86e17bde489a
Revises: 09d9469046c4
Create Date: 2026-04-13 18:30:50.459930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e17bde489a'
down_revision: Union[str, Sequence[str], None] = '09d9469046c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('learner_summary', sa.Text(), nullable=True))
    op.add_column('learner_profiles', sa.Column('summary_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_profiles', 'summary_updated_at')
    op.drop_column('learner_profiles', 'learner_summary')
    # ### end Alembic commands ###
